### PR TITLE
i2pd: Compilation fix for MIPS targets

### PR DESCRIPTION
**Pull request by Shulyaka**

### CODE REVIEW

**Comment by ryzhovau** [comment]
Hi!

What MIPS Targets? We've got only one MIPS target, which is compiled with no any issues.

**Comment by Shulyaka** [comment]
I use this package on a different hardware in a general LEDE distribution. I believe this PR might be helpful for other LEDE/OpenWrt users that want to use i2pd on their routers.
If you don't want to support this kind of use, would you mind if I add the package with my own modifications to the openwrt/packages repo and will maintain it there?

**Comment by zyxmon** [comment]
@Shulyaka please post it in Entware-3x fork with mips be feed
https://github.com/Entware-for-kernel-3x

**Comment by ryzhovau** [comment]
> If you don't want to support this kind of use, would you mind if I add the package with my own modifications to the openwrt/packages repo and will maintain it there?

Sure. Feel free to use this sources as you wish.

**Pull request closed without merging**
